### ISSUE TITLE
Plex Channel only showing 21 of 43 channels.

### ISSUE THREAD

**Issue by MaestroJAL** [Jidly/channelpear.bundle#2]
First off, thanks for this bundle.  I've noticed that no matter how many channels I add to my media database, the channel only shows 21.  I thought it was the top 21 channels alphabetically but it seems to be arbitrary.

**Comment by MaestroJAL** [comment]
Seems to be a feature, not a bug as the missing channels had stopped working even though they were listed as "verified".

**Comment by jasonbio** [comment]
Sorry for not getting to this sooner. I think you figured it out though. The channel blocks Smooth Streaming sources by default since Plex doesn't work with them. Hope that helps! :)
